export const API = "http://127.0.0.1:5000"
export const API_IMAGE_URL = "http://127.0.0.1:5000/static/images/"

export const API_LOGIN = "/auth"
export const API_SIGNUP = "/add_user"
export const API_GET_USERS = "/users"
export const API_GET_ME = "/users/"
export const API_EDIT_PROFILE ="/edit_user/"
export const API_POSTS = "/add_blog"
export const API_GET = "/blogs"
export const API_GET_SP ="/blog/"
export const API_GET_GAL = "/gallery"
export const API_EDIT = "/update_blog/"
export const API_DELETE = "/delete_blog/"
export const API_LIKE = "/likes/"
export const API_FB = "/add_comment/"
export const API_GET_FB = "get_comment/"
export const API_SEARCH = "/search"
export const API_WHOAMI = "/whoami"


